/**
 * GENERATED by scripts/port-art.mjs from docs/design/mockups/sprites.js — do not edit by hand.
 * Regenerate with `node scripts/port-art.mjs` after changing the source art.
 */

import type { OverlaysData } from './types.ts';

/** HUD/canvas overlay art: fonts, digits, pips, hover/selected/refuse marks, fuse, ring… */
export const OVERLAYS: OverlaysData = {
  "font3x5": {
    "0": [
      "###",
      "#.#",
      "#.#",
      "#.#",
      "###"
    ],
    "1": [
      ".#.",
      "##.",
      ".#.",
      ".#.",
      "###"
    ],
    "2": [
      "###",
      "..#",
      "###",
      "#..",
      "###"
    ],
    "3": [
      "###",
      "..#",
      ".##",
      "..#",
      "###"
    ],
    "4": [
      "#.#",
      "#.#",
      "###",
      "..#",
      "..#"
    ],
    "5": [
      "###",
      "#..",
      "###",
      "..#",
      "###"
    ],
    "6": [
      "###",
      "#..",
      "###",
      "#.#",
      "###"
    ],
    "7": [
      "###",
      "..#",
      ".#.",
      ".#.",
      ".#."
    ],
    "8": [
      "###",
      "#.#",
      "###",
      "#.#",
      "###"
    ],
    "9": [
      "###",
      "#.#",
      "###",
      "..#",
      "###"
    ]
  },
  "digits": {
    "0": [
      "ooooo",
      "owwwo",
      "owowo",
      "owowo",
      "owowo",
      "owwwo",
      "ooooo"
    ],
    "1": [
      ".ooo.",
      "oowo.",
      "owwo.",
      "oowo.",
      "oowoo",
      "owwwo",
      "ooooo"
    ],
    "2": [
      "ooooo",
      "owwwo",
      "ooowo",
      "owwwo",
      "owooo",
      "owwwo",
      "ooooo"
    ],
    "3": [
      "ooooo",
      "owwwo",
      "ooowo",
      ".owwo",
      "ooowo",
      "owwwo",
      "ooooo"
    ],
    "4": [
      "ooooo",
      "owowo",
      "owowo",
      "owwwo",
      "ooowo",
      "..owo",
      "..ooo"
    ],
    "5": [
      "ooooo",
      "owwwo",
      "owooo",
      "owwwo",
      "ooowo",
      "owwwo",
      "ooooo"
    ],
    "6": [
      "ooooo",
      "owwwo",
      "owooo",
      "owwwo",
      "owowo",
      "owwwo",
      "ooooo"
    ],
    "7": [
      "ooooo",
      "owwwo",
      "ooowo",
      ".owoo",
      ".owo.",
      ".owo.",
      ".ooo."
    ],
    "8": [
      "ooooo",
      "owwwo",
      "owowo",
      "owwwo",
      "owowo",
      "owwwo",
      "ooooo"
    ],
    "9": [
      "ooooo",
      "owwwo",
      "owowo",
      "owwwo",
      "ooowo",
      "owwwo",
      "ooooo"
    ]
  },
  "digitsAnchor": {
    "anchorX": 2,
    "gapAboveSprite": 2
  },
  "pips": {
    "plate": "o",
    "full": "c",
    "warn": "F",
    "empty": "K",
    "w": 13,
    "h": 5,
    "cols": 6,
    "rows": 2,
    "warnAt": 3,
    "example12": [
      "ooooooooooooo",
      "ococococococo",
      "ooooooooooooo",
      "ococococococo",
      "ooooooooooooo"
    ],
    "example3": [
      "ooooooooooooo",
      "oFoFoFoKoKoKo",
      "ooooooooooooo",
      "oKoKoKoKoKoKo",
      "ooooooooooooo"
    ]
  },
  "hover": {
    "rows": [
      "www.......www",
      "w...........w",
      "w...........w",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      "w...........w",
      "w...........w",
      "www.......www"
    ],
    "anchorX": 6,
    "anchorY": 13
  },
  "selected": {
    "rows": [
      ".....ooooo....",
      ".....otttoo...",
      "......otoo....",
      ".......o......",
      "tttt......tttt",
      "tooo......ooot",
      "to..........ot",
      "to..........ot",
      "..............",
      "..............",
      "..............",
      "..............",
      "..............",
      "..............",
      "..............",
      "..............",
      "to..........ot",
      "to..........ot",
      "tooo......ooot",
      "tttt......tttt"
    ],
    "anchorX": 6,
    "anchorY": 17
  },
  "crosshair": {
    "rows": [
      "....o....",
      "...owo...",
      "...owo...",
      "oooo.oooo",
      "owww.wwwo",
      "oooo.oooo",
      "...owo...",
      "...owo...",
      "....o...."
    ],
    "anchorX": 4,
    "anchorY": 4
  },
  "steelSpark": {
    "frames": [
      [
        "...f...",
        ".f.F.f.",
        "..fwf..",
        "fFwwwFf",
        "..fwf..",
        ".f.F.f.",
        "...f..."
      ],
      [
        "f..f..f",
        ".......",
        "...w...",
        "f.www.f",
        "...w...",
        ".......",
        "f..f..f"
      ]
    ],
    "anchorX": 3,
    "anchorY": 3,
    "ticksPerFrame": 2
  },
  "refusal": {
    "rows": [
      "ooo...ooo",
      "orro.orro",
      "oorrorroo",
      ".oorrroo.",
      "..orwro..",
      ".oorrroo.",
      "oorrorroo",
      "orro.orro",
      "ooo...ooo"
    ],
    "anchorX": 4,
    "anchorY": 4
  },
  "pending": {
    "rows": [
      ".ooooooo.",
      "owwwwwwwo",
      "owooooooo",
      "owwotowwo",
      "owwwowwwo",
      "owwotowwo",
      "owooooooo",
      "owwwwwwwo",
      ".ooooooo.",
      "...ooo...",
      "....o...."
    ],
    "anchorX": 4,
    "anchorY": 10
  },
  "fuse": {
    "frames": [
      [
        ".f.",
        "fFf",
        ".f."
      ],
      [
        "f.f",
        ".F.",
        "f.f"
      ]
    ],
    "anchorX": 1,
    "anchorY": 2,
    "ticksPerFrame": 2
  },
  "assignRing": {
    "frames": [
      [
        "..www..",
        ".w...w.",
        "w.....w",
        "w.....w",
        "w.....w",
        ".w...w.",
        "..www.."
      ],
      [
        "...w.w...",
        ".w.....w.",
        ".........",
        "w.......w",
        ".........",
        "w.......w",
        ".........",
        ".w.....w.",
        "...w.w..."
      ]
    ],
    "ticksPerFrame": 2
  }
};
