/**
 * GENERATED by scripts/port-art.mjs from docs/design/mockups/sprites.js — do not edit by hand.
 * Regenerate with `node scripts/port-art.mjs` after changing the source art.
 */

/** Mumble sprite palette: one char key → '#rrggbb' (31 keys). */
export const MUMBLE_PALETTE: Readonly<Record<string, string>> = {
  "o": "#2a1433",
  "b": "#ff8a65",
  "B": "#d9573f",
  "h": "#ffc4a3",
  "c": "#fff1d6",
  "t": "#ffc93c",
  "T": "#d98e0f",
  "w": "#ffffff",
  "p": "#140a1a",
  "r": "#ef3e55",
  "R": "#a8243c",
  "s": "#9a6a3c",
  "l": "#f4c46a",
  "L": "#b77a2c",
  "m": "#3fd0c9",
  "M": "#1f8a86",
  "g": "#e3e9f0",
  "G": "#8b96a6",
  "d": "#fffaf0",
  "D": "#c9bde3",
  "e": "#8f7bb0",
  "q": "#ff5fa8",
  "f": "#fff5a0",
  "F": "#ff8a1f",
  "y": "#bff0ff",
  "a": "#4a3a46",
  "A": "#ff6a2a",
  "k": "#b4a8b8",
  "K": "#7d7084",
  "x": "#ffe45c",
  "n": "#0c0816"
};
