/**
 * GENERATED by scripts/port-art.mjs from docs/design/mockups/sprites.js — do not edit by hand.
 * Regenerate with `node scripts/port-art.mjs` after changing the source art.
 */

import type { Theme, ThemeId } from './themes.ts';

/** The 5 shipped themes' full art + colour-role data. */
export const THEMES: Readonly<Record<ThemeId, Theme>> = {
  "mossgrove": {
    "id": "mossgrove",
    "name": "Mossgrove",
    "mood": "Twilight forest floor: sage stones blanketed in glowing moss, fireflies, a peat bog.",
    "background": "#16122c",
    "palette": [
      "#000000",
      "#557a63",
      "#6a9274",
      "#84ab86",
      "#a3c79b",
      "#b8e04a",
      "#e9ff9a",
      "#5a6886",
      "#8494b4",
      "#b5c4de",
      "#a0664f",
      "#5e3a35",
      "#c98a68",
      "#f0dfb4",
      "#ffe27a",
      "#2a1433",
      "#c79a5a",
      "#7fcf9a",
      "#3f7f68",
      "#d8f5c8",
      "#6fb83f",
      "#2f6a2a",
      "#e8475f",
      "#a8764a",
      "#6e4a30",
      "#c9a36a",
      "#ffe98a",
      "#ffe98a"
    ],
    "earth": [
      1,
      2,
      3,
      4
    ],
    "surface": 5,
    "surfaceHi": 6,
    "steel": [
      7,
      8,
      9
    ],
    "bricks": [
      10,
      11
    ],
    "brickHi": 12,
    "builderBrick": 13,
    "oneWay": 14,
    "oneWayEdge": 15,
    "accent": 16,
    "hazard": [
      17,
      18,
      19
    ],
    "trap": [
      20,
      21,
      22
    ],
    "hatch": [
      23,
      24
    ],
    "exit": [
      25,
      26
    ],
    "decor": 27,
    "hazardKind": "water",
    "hazardName": "bog pool",
    "trapName": "snapjaw flytrap",
    "texture": {
      "dripMax": 3,
      "strataBands": [
        3,
        3,
        2,
        2,
        16,
        2,
        1,
        1,
        2,
        3,
        4,
        3
      ],
      "brick": [
        8,
        4
      ],
      "mossOnBricks": true
    },
    "minimap": {
      "terrain": "#84ab86",
      "steel": "#8494b4",
      "hazard": "#ff7470",
      "exit": "#ffffff",
      "mumble": "#ffc93c",
      "view": "#f7f3ff"
    }
  },
  "sugarworks": {
    "id": "sugarworks",
    "name": "Sugarworks",
    "mood": "A cosy sweet factory: gingerbread cliffs under pink frosting, chocolate walls, hot caramel.",
    "background": "#2a1024",
    "palette": [
      "#000000",
      "#a8653a",
      "#c47d48",
      "#dc9a5c",
      "#efbb7c",
      "#ff9fd0",
      "#fff2fa",
      "#3f6e70",
      "#6ea3a1",
      "#b3e0d8",
      "#a86443",
      "#5c2c1e",
      "#cf8a60",
      "#f8dc98",
      "#ffffff",
      "#b0184f",
      "#fff0d8",
      "#ffb53d",
      "#d8731a",
      "#fff0a8",
      "#d6dde6",
      "#7c8898",
      "#ef3e55",
      "#ef3e55",
      "#fff2fa",
      "#fff2fa",
      "#ffd46a",
      "#ff9fd0"
    ],
    "earth": [
      1,
      2,
      3,
      4
    ],
    "surface": 5,
    "surfaceHi": 6,
    "steel": [
      7,
      8,
      9
    ],
    "bricks": [
      10,
      11
    ],
    "brickHi": 12,
    "builderBrick": 13,
    "oneWay": 14,
    "oneWayEdge": 15,
    "accent": 16,
    "hazard": [
      17,
      18,
      19
    ],
    "trap": [
      20,
      21,
      22
    ],
    "hatch": [
      23,
      24
    ],
    "exit": [
      25,
      26
    ],
    "decor": 27,
    "hazardKind": "fire",
    "hazardName": "hot caramel",
    "trapName": "cookie-cutter press",
    "texture": {
      "dripMax": 5,
      "strataBands": [
        3,
        3,
        3,
        16,
        16,
        2,
        2,
        5,
        2,
        2,
        16,
        3
      ],
      "brick": [
        6,
        5
      ],
      "mossOnBricks": false
    },
    "minimap": {
      "terrain": "#dc9a5c",
      "steel": "#6ea3a1",
      "hazard": "#ff7470",
      "exit": "#ffffff",
      "mumble": "#ffc93c",
      "view": "#f7f3ff"
    }
  },
  "observatory": {
    "id": "observatory",
    "name": "Starfrost Observatory",
    "mood": "A hushed hilltop observatory at midnight: frosted periwinkle stone, brass fittings, star-chart tiles.",
    "background": "#0b0f2e",
    "palette": [
      "#000000",
      "#5d6fa8",
      "#7385bf",
      "#8fa0d4",
      "#b2c0ea",
      "#e6f6ff",
      "#ffffff",
      "#86652a",
      "#bd9242",
      "#ecc870",
      "#8a70c8",
      "#3d2f78",
      "#b39ef0",
      "#ffe3a3",
      "#ffd966",
      "#1a1f4d",
      "#f2cd63",
      "#8fe3ff",
      "#3f9fd0",
      "#ffffff",
      "#d9a441",
      "#6e4f1d",
      "#e8eef8",
      "#b88c3c",
      "#6e4f1d",
      "#ecc870",
      "#b8e6ff",
      "#ffffff"
    ],
    "earth": [
      1,
      2,
      3,
      4
    ],
    "surface": 5,
    "surfaceHi": 6,
    "steel": [
      7,
      8,
      9
    ],
    "bricks": [
      10,
      11
    ],
    "brickHi": 12,
    "builderBrick": 13,
    "oneWay": 14,
    "oneWayEdge": 15,
    "accent": 16,
    "hazard": [
      17,
      18,
      19
    ],
    "trap": [
      20,
      21,
      22
    ],
    "hatch": [
      23,
      24
    ],
    "exit": [
      25,
      26
    ],
    "decor": 27,
    "hazardKind": "water",
    "hazardName": "icy meltwater",
    "trapName": "brass pendulum",
    "texture": {
      "dripMax": 2,
      "strataBands": [
        2,
        2,
        3,
        3,
        4,
        16,
        3,
        2,
        2,
        1,
        2,
        3
      ],
      "brick": [
        8,
        8
      ],
      "mossOnBricks": false
    },
    "minimap": {
      "terrain": "#8fa0d4",
      "steel": "#bd9242",
      "hazard": "#ff7470",
      "exit": "#ffffff",
      "mumble": "#ffc93c",
      "view": "#f7f3ff"
    }
  },
  "foundry": {
    "id": "foundry",
    "name": "Cogwork Foundry",
    "mood": "A busy casting floor: warm ochre moulding sand, blued-iron plates, firebrick, molten brass.",
    "background": "#181114",
    "palette": [
      "#000000",
      "#8f6a3c",
      "#a9804a",
      "#c49a5c",
      "#dcb574",
      "#f3dc9c",
      "#ff9a4a",
      "#44648a",
      "#6a8fb8",
      "#9ec0e4",
      "#b8583c",
      "#6a2c20",
      "#dc7c5c",
      "#f4e2b8",
      "#7ff0ff",
      "#0f2233",
      "#e08a4a",
      "#ffd24a",
      "#ff8a1c",
      "#fff4b0",
      "#8ea6c4",
      "#34506f",
      "#ffd24a",
      "#8a929c",
      "#3c3c44",
      "#c8d0da",
      "#7dff9a",
      "#ff9a4a"
    ],
    "earth": [
      1,
      2,
      3,
      4
    ],
    "surface": 5,
    "surfaceHi": 6,
    "steel": [
      7,
      8,
      9
    ],
    "bricks": [
      10,
      11
    ],
    "brickHi": 12,
    "builderBrick": 13,
    "oneWay": 14,
    "oneWayEdge": 15,
    "accent": 16,
    "hazard": [
      17,
      18,
      19
    ],
    "trap": [
      20,
      21,
      22
    ],
    "hatch": [
      23,
      24
    ],
    "exit": [
      25,
      26
    ],
    "decor": 27,
    "hazardKind": "fire",
    "hazardName": "molten brass",
    "trapName": "piston hammer",
    "texture": {
      "dripMax": 2,
      "strataBands": [
        2,
        2,
        3,
        3,
        3,
        16,
        2,
        2,
        1,
        2,
        4,
        3
      ],
      "brick": [
        8,
        4
      ],
      "mossOnBricks": false
    },
    "minimap": {
      "terrain": "#c49a5c",
      "steel": "#6a8fb8",
      "hazard": "#ff7470",
      "exit": "#ffffff",
      "mumble": "#ffc93c",
      "view": "#f7f3ff"
    }
  },
  "reef": {
    "id": "reef",
    "name": "Tidepool Reef",
    "mood": "A sunlit rock pool seen from below: violet reef rock, golden sand, a sunken ship hull, foamy tide.",
    "background": "#04202c",
    "palette": [
      "#000000",
      "#7d6bb4",
      "#9180c8",
      "#a898d8",
      "#c4b8e8",
      "#f2d99a",
      "#fff6de",
      "#357a73",
      "#55a89d",
      "#8fd8c8",
      "#b58f6c",
      "#5e4636",
      "#d4b08c",
      "#ecd3a2",
      "#ffffff",
      "#0a2a3a",
      "#ff9cc4",
      "#5fdcef",
      "#1f8fb0",
      "#f0ffff",
      "#b58ad6",
      "#6a4a8e",
      "#ffd1e8",
      "#c49a64",
      "#6e4e34",
      "#e0b85a",
      "#9ff6ff",
      "#9ff6ff"
    ],
    "earth": [
      1,
      2,
      3,
      4
    ],
    "surface": 5,
    "surfaceHi": 6,
    "steel": [
      7,
      8,
      9
    ],
    "bricks": [
      10,
      11
    ],
    "brickHi": 12,
    "builderBrick": 13,
    "oneWay": 14,
    "oneWayEdge": 15,
    "accent": 16,
    "hazard": [
      17,
      18,
      19
    ],
    "trap": [
      20,
      21,
      22
    ],
    "hatch": [
      23,
      24
    ],
    "exit": [
      25,
      26
    ],
    "decor": 27,
    "hazardKind": "water",
    "hazardName": "foamy tide pool",
    "trapName": "snapping giant clam",
    "texture": {
      "dripMax": 3,
      "strataBands": [
        2,
        2,
        3,
        3,
        16,
        3,
        4,
        3,
        2,
        1,
        2,
        16
      ],
      "brick": [
        8,
        6
      ],
      "mossOnBricks": false
    },
    "minimap": {
      "terrain": "#a898d8",
      "steel": "#55a89d",
      "hazard": "#ff7470",
      "exit": "#ffffff",
      "mumble": "#ffc93c",
      "view": "#f7f3ff"
    }
  }
};
