/**
 * Visual themes. A theme is a small indexed palette plus the roles each index plays; terrain
 * stores palette INDICES (0 = transparent), so recolouring a theme never touches level data.
 * Data lives in `theme-data.ts`, GENERATED by `scripts/port-art.mjs` from
 * `docs/design/mockups/sprites.js` → `themes` (the single source of truth for theme art).
 */
import type { HazardKind } from '../core/types.ts';
import { THEMES as THEME_DATA } from './theme-data.ts';

export const THEME_IDS = ['mossgrove', 'sugarworks', 'observatory', 'foundry', 'reef'] as const;
export type ThemeId = (typeof THEME_IDS)[number];

export interface Theme {
  readonly id: ThemeId;
  readonly name: string;
  /** One-line mood/flavour text (briefing/level-select copy). */
  readonly mood: string;
  /** CSS colour behind the terrain. */
  readonly background: string;
  /** Index → '#rrggbb'. Index 0 is reserved (transparent). Max 256 entries. */
  readonly palette: readonly string[];
  /** Indices for natural earth shading, dark → light. */
  readonly earth: readonly number[];
  /** Index for the lit top surface of earth (grass, moss, frost…). */
  readonly surface: number;
  /** Index for a brighter highlight on the lit top surface. */
  readonly surfaceHi: number;
  /** Indices for steel, dark → light. */
  readonly steel: readonly number[];
  /** Indices for brick fill: [brick, mortar]. */
  readonly bricks: readonly [number, number];
  /** Index for a highlight on brick fill (e.g. moss-on-bricks accents). */
  readonly brickHi: number;
  /** Index used for builder bricks placed during play. */
  readonly builderBrick: number;
  /** Index for one-way arrow markings. */
  readonly oneWay: number;
  /** Index for the one-way wall's edge/frame. */
  readonly oneWayEdge: number;
  /** General-purpose accent index (UI/decor highlights). */
  readonly accent: number;
  /** Hazard pool indices: [surface, deep, foam]. */
  readonly hazard: readonly [number, number, number];
  /** Trap indices: [main, dark, accent]. */
  readonly trap: readonly [number, number, number];
  /** Hatch (entrance) indices: [main, dark]. */
  readonly hatch: readonly [number, number];
  /** Exit indices: [rim, glow]. */
  readonly exit: readonly [number, number];
  /** Index for background decoration primitives (LevelDef.decor). */
  readonly decor: number;
  /** What kind of HazardDef this theme's hazard pool renders as. */
  readonly hazardKind: HazardKind;
  /** Flavour name for the hazard (briefing copy), e.g. "bog pool". */
  readonly hazardName: string;
  /** Flavour name for the trap (briefing copy), e.g. "snapjaw flytrap". */
  readonly trapName: string;
  readonly texture: {
    /** Max drip length under overhangs (texture recipe). */
    readonly dripMax: number;
    /** 12 row-band weights for the strata fill recipe. */
    readonly strataBands: readonly number[];
    /** Brick tile size [w, h] for the bricks fill recipe. */
    readonly brick: readonly [number, number];
    /** Whether moss/growth accents appear on brick fills. */
    readonly mossOnBricks: boolean;
  };
  readonly minimap: {
    readonly terrain: string;
    readonly steel: string;
    readonly hazard: string;
    readonly exit: string;
    readonly mumble: string;
    readonly view: string;
  };
}

export const THEMES: Readonly<Record<ThemeId, Theme>> = THEME_DATA;

export function getTheme(id: string): Theme {
  return (THEMES as Record<string, Theme>)[id] ?? THEMES.mossgrove;
}
