// `node scripts/port-art.mjs` — regenerates src/art/{palette,mumble,objects,icons,overlays}.ts
// and src/levels/theme-data.ts from docs/design/mockups/sprites.js (window.MUMBLE_ART), the
// single source of truth for pixel art. Deterministic and re-runnable: never hand-edit the
// generated files — fix this script or the source data instead.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = path.join(root, 'docs/design/mockups/sprites.js');
const source = readFileSync(sourcePath, 'utf8');

const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(source, sandbox, { filename: sourcePath });
const ART = sandbox.window.MUMBLE_ART;
if (!ART || typeof ART !== 'object') {
  throw new Error(`${sourcePath} did not set window.MUMBLE_ART`);
}
for (const key of ['palette', 'sprites', 'objects', 'icons', 'overlays', 'themes']) {
  if (!ART[key]) throw new Error(`window.MUMBLE_ART.${key} is missing from sprites.js`);
}

const HEADER =
  '/**\n' +
  ' * GENERATED by scripts/port-art.mjs from docs/design/mockups/sprites.js — do not edit by hand.\n' +
  ' * Regenerate with `node scripts/port-art.mjs` after changing the source art.\n' +
  ' */\n';

/** Deterministic pretty-printer: JSON.stringify preserves key/array order from the vm parse. */
const json = (value) => JSON.stringify(value, null, 2);

function write(relPath, body) {
  writeFileSync(path.join(root, relPath), body, 'utf8');
  console.log(`wrote ${relPath}`);
}

write(
  'src/art/palette.ts',
  `${HEADER}
/** Mumble sprite palette: one char key → '#rrggbb' (31 keys). */
export const MUMBLE_PALETTE: Readonly<Record<string, string>> = ${json(ART.palette)};
`,
);

write(
  'src/art/mumble.ts',
  `${HEADER}
import type { LemmingState } from '../core/types.ts';
import type { Anim } from './anim.ts';

/** One animation per lemming state (DESIGN §3.4): frames, timing and the foot anchor. */
export const MUMBLE_ANIMS: Readonly<Record<LemmingState, Anim>> = ${json(ART.sprites)};
`,
);

write(
  'src/art/objects.ts',
  `${HEADER}
import type { ArtThemeId, ThemeObjects } from './types.ts';

/** Entrance/exit/trap/hazard art per theme (same field names as sprites.js). */
export const THEME_OBJECTS: Readonly<Record<ArtThemeId, ThemeObjects>> = ${json(ART.objects)};
`,
);

const iconMeta = ART.icons['meta'];
const iconFrames = Object.fromEntries(Object.entries(ART.icons).filter(([key]) => key !== 'meta'));
write(
  'src/art/icons.ts',
  `${HEADER}
import type { PixelFrame } from './anim.ts';

/** 16×16 HUD icons: the 8 skills + rrMinus, rrPlus, pause, fastForward, popAll. */
export const ICONS: Readonly<Record<string, PixelFrame>> = ${json(iconFrames)};

/** Display order for the icon strip / HUD toolbar. */
export const ICON_ORDER: readonly string[] = ${json(iconMeta.order)};

/** Accessible label per icon id. */
export const ICON_LABELS: Readonly<Record<string, string>> = ${json(iconMeta.labels)};
`,
);

write(
  'src/art/overlays.ts',
  `${HEADER}
import type { OverlaysData } from './types.ts';

/** HUD/canvas overlay art: fonts, digits, pips, hover/selected/refuse marks, fuse, ring… */
export const OVERLAYS: OverlaysData = ${json(ART.overlays)};
`,
);

write(
  'src/levels/theme-data.ts',
  `${HEADER}
import type { Theme, ThemeId } from './themes.ts';

/** The 5 shipped themes' full art + colour-role data. */
export const THEMES: Readonly<Record<ThemeId, Theme>> = ${json(ART.themes)};
`,
);

console.log('Art port complete.');
